networks:
  garbage-network:
    driver: bridge

services:
  spark-service:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: ninerem/garbage-spark-service:latest
    container_name: garbage-spark-service
    networks:
      - garbage-network
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - garbage-data:/app/data
      - shared-models:/app/models
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped

  streamlit-front:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    image: ninerem/garbage-streamlit-front:latest
    container_name: garbage-streamlit-front
    networks:
      - garbage-network
    depends_on:
      - spark-service
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - garbage-data:/app/data
      - shared-models:/app/models
    restart: unless-stopped

  trainer:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: ninerem/garbage-spark-service:latest
    container_name: garbage-training-service
    networks:
      - garbage-network
    depends_on:
      - spark-service
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - garbage-data:/app/data
      - shared-models:/app/models
    working_dir: /app
    command: ["python", "src/train_loop.py"]
    restart: unless-stopped

  prediction:
    image: ninerem/garbage-spark-service:latest
    container_name: garbage-prediction-service
    networks:
      - garbage-network
    depends_on:
      - spark-service
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - garbage-data:/app/data
      - shared-models:/app/models
    working_dir: /app
    command: ["python", "src/run_prediction.py"]
    restart: "no"

volumes:
  garbage-data:
  shared-models:
