networks:
    garbage-network:
        driver: bridge

services:
    spark-service:
        build:
            context: .
            dockerfile: Dockerfile.spark
        image: ninerem/garbage-spark-service:latest
        container_name: garbage-spark-service
        env_file:
            - .env
        volumes:
            - ./data:/app/data
            - ./models:/app/models
            - ./parquet:/app/database
        working_dir: /app
        command: ["data/data_transformation.py"]

    keras-service:
        build:
            context: .
            dockerfile: Dockerfile.spark
        image: ninerem/garbage-keras-service:latest
        container_name: garbage-keras-service
        env_file:
            - .env
        volumes:
            - ./parquet:/app/database
            - ./models:/app/models
        working_dir: /app
        command: ["models/training.py"]

    api-service:
        build:
            context: .
            dockerfile: Dockerfile.api
        image: ninerem/garbage-api-service:latest
        container_name: garbage-api-service
        networks:
            - garbage-network
        env_file:
            - .env
        volumes:
            - ./data:/app/data
        working_dir: /app
        restart: unless-stopped

    streamlit-front:
        build:
            context: .
            dockerfile: Dockerfile.streamlit
        image: ninerem/garbage-streamlit-front:latest
        container_name: garbage-streamlit-front
        networks:
            - garbage-network
        depends_on:
            - api-service
        env_file:
            - .env
        volumes:
            - ./src:/app/src
        ports:
            - "8501:8501"
        restart: unless-stopped
