networks:
  garbage-network:
    driver: bridge

services:
  spark-service:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: ninerem/garbage-spark-service:latest
    container_name: garbage-spark-service
    networks:
      - garbage-network
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - garbage-data:/app/data
      - shared-models:/app/models
    restart: unless-stopped

volumes:
  garbage-data:
  shared-models:
